### ISSUE TITLE
streaming response

### ISSUE THREAD

**Issue by yosun** [david-wei-01001/CSharp-Unity-to-Google-Vertex-AI#1]
can you add in streaming chat response

**Comment by david-wei-01001** [comment]
Please go to AIHttpClients.cs/MyRegion, and change QUERY to:
```CS
protected static string QUERY = "streamGenerateContent";
```
More information can be seen at:
https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal
